import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Projeto Computador',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className='bg-[#303030]'>{children}</body>
    </html>
  )
}